### ISSUE TITLE
I have only saw datepicker from source code, will we support time picker?

### ISSUE THREAD

**Issue by jinzhu** [dgrubelic/material-design-lite#14]

**Comment by dgrubelic** [comment]
Time picker will probably be a separate component. Since material design specs are not so detailed about this component, we'll need guidance from MDL design team whether to combine those two components in one.

google/material-design-lite#1695

**Comment by sgomes** [comment]
Yes, I agree it makes sense to have it as a separate component. This is more of a technical decision, though, so I don't think we need to involve the Material Design team.

To me, they look like fundamentally different components; the UI is going to be completely different in both modes anyway, so I don't see a lot of benefit in cramming both modes into a single component.

**Comment by dgrubelic** [comment]
So, time picker will be totally different component from date picker. It's just that i dont know when will i start working on implementation.

**Comment by jinzhu** [comment]
Btw, how about datetime picker, is it supported?

**Comment by dgrubelic** [comment]
From what i saw in MD specs, no, datetime picker is not supported. They are two totally different components. And i think that there is no reason to introduce another component which isn't defined by specs can be done using date and time components separate.
