### ISSUE TITLE
Backdrop places over datapicker

### ISSUE THREAD

**Issue by vasia123** [dgrubelic/material-design-lite#15]
If datapicker places inside template with "Scrolling header" -http://getmdl.io/components/index.html#layout/scrolling-header.html (where `<!-- Your content goes here -->`) then backdrop places over datapicker.

Screenshot: https://yadi.sk/i/6bjl8zXCpssPE

**Comment by dgrubelic** [comment]
Thanks for reporting this. I'll check it out as soon as i fix other issues reported in my PR in origin repo. Maybe it's related with something reported over there.

**Comment by dgrubelic** [comment]
The issue was with date picker widget placed inside layout. This should be fixed now.

**Comment by avanturist888** [comment]
Thank you! Now it works as expected!
