### ISSUE TITLE
Fixed date picker behind mdl dialog

### ISSUE THREAD

**Issue by dgrubelic** [dgrubelic/material-design-lite#17]
Should investigate this, but it seams that now fixed date picker can't be shown inside dialog as it appears behind mdl dialog window.

**Comment by dgrubelic** [comment]
Dialog windows are always rendered on top of entire page content, so if date picker is appended to body (in order to behave well with other MDL components like Layout), fixed date picker is always rendered behind modal dialog window.

**Comment by RanzQ** [comment]
This can be solved by using `.show()` instead of `.showModal()` and then adjusting the css a bit to center the dialog vertically. I'm using [pikaday](https://github.com/dbushell/Pikaday) but the issue should be same.

**Comment by dgrubelic** [comment]
I'll try this solution and see how it goes. Thanks for suggestion. :)

**Comment by RanzQ** [comment]
The problem is that native dialogs are rendered on top of everything. But with `.show()` it's added to body.

**Comment by dgrubelic** [comment]
Yes, but that way i must add backdrop element manually which is not what is required behaviour.
