### ISSUE TITLE
Possible to change first day of week?

### ISSUE THREAD

**Issue by RanzQ** [dgrubelic/material-design-lite#22]
This would be a good feature in datepicker if not yet supported. In many locales week starts from monday (ISO 8601).

**Comment by dgrubelic** [comment]
This has already been reported and PR merged into my branch.

``` javascript
// Week starts on monday
DatePicker.locales.weekStart = 1;
```

add weekStart to settings #16

**Comment by RanzQ** [comment]
Oh, cool.
