### ISSUE TITLE
Approve merge with MDL

### ISSUE THREAD

**Issue by XcrossD** [dgrubelic/material-design-lite#30]
I would like to use a MDL date-picker, then I saw that you have worked out a PR, which is very nice! But it seems that you told MDL team not to merge due to bug fixes. Your issue tracker only has 1 issue labeled as bug, and that is already a few months old. In addition, I tried out your demo and didn't really find any bugs (Firefox 47.0, Windows 10). If that issue is solved, perhaps you could greenlight the merge with MDL? Thank you for creating this component. Let me know if there is anything I can help with to speed up the process.

**Comment by dgrubelic** [comment]
It took me some time to do it, but PR finally submitted.
