### ISSUE TITLE
Datepicker styling problems

### ISSUE THREAD

**Issue by ailic** [dgrubelic/material-design-lite#31]
Hi,
I have the following scenario and problems with styles, which are, for some reasons, not completely applied.

I've cloned the original _material-design-lite_ repo, and also the repo of yours. I've checkout the _datepicker_ branch. Since complete implementation is included in one commit, I've made a patch and applied it to the original repo. Once the build is done (no errors), I get this:

![screenshot from 2016-10-27 01 17 31](https://cloud.githubusercontent.com/assets/390496/19748896/0ea74294-9be5-11e6-8a57-781143c567c8.png)

Code behind:

``` html
<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-datepicker mdl-js-datepicker">
    <input type="text" class="mdl-textfield__input mdl-datepicker__input" id="fldSD">
    <label for="fldSD" class="mdl-textfield__label">Start date</label>
</div>
```

If I build your repo, demo works fine, and there are no color issues.

Thanks!

**Comment by ailic** [comment]
Here's the answer to the problem described above. In the newer version of MDL, color variables are handled a bit different. Since they're defined as RGB values, you cannot use them anymore like  

``` scss
$datepicker-bg-color: $color-white !default;
```

but

``` scss
$datepicker-bg-color: unquote("rgb(#{$color-white})") !default;
```

So, in order to render your component correctly, changes should be applied to all `$datepicker-*` variables in `src/_variables.scss` file.

I'll keep this issue opened, and you can close it once you adapt your code to work on the newest version of MDL 1 (`mdl-1-x`).

**Comment by dgrubelic** [comment]
Hi @ailic, thank you for reporting this. I will try to update datepicker component to new version and submit PR soon.

**Comment by dgrubelic** [comment]
PR submitted.
