### ISSUE TITLE
Implement date ranges

### ISSUE THREAD

**Issue by dgrubelic** [dgrubelic/material-design-lite#8]
Include minimum and maximum dates and control picker available dates.

Should check with Google guys if this is really necessary for this component or should we let users to implement that kind of checks.

**Comment by dgrubelic** [comment]
Should check with Google guys if this is really necessary for this component or should we let users to implement that kind of checks.

**Comment by sgomes** [comment]
You could add the ability to the component to validate user-defined minimum and maximum dates, but given that there isn't even any example in the spec of how the error message would be displayed (unlike, e.g. text fields), this sort of validation is probably better left to users.

Thanks again for looking into this component!

**Comment by dgrubelic** [comment]
I was thinking to implement possibility do disable date selection outside of defined range. That way we don't need validation since date selection is impossible. This feature is actually implemented in Material UI date-picker (http://www.material-ui.com/#/components/date-picker).

No problem. I need the component and I, since nobody took the job before, decided to write it myself. Hope it will be good enough for public release.

**Comment by sgomes** [comment]
@dgrubelic Happy for you to proceed either way on this, just giving you the perspective on what the spec requires.

Don't worry about public release; we'll be sure to review it thoroughly and help you with making any changes needed. And we'll take good care of it afterwards :) Thanks again for working on this!

**Comment by jinzhu** [comment]
Hi @dgrubelic 

What's the state of this issue, any update?

**Comment by dgrubelic** [comment]
Hi @jinzhu thanks for interest... I had to take some time off for other personal stuff do resolve before  working on this one. I believe that i will have this finished by the end of this week.

**Comment by jinzhu** [comment]
@dgrubelic cool, thank you for the update.
